/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package optimizador.optimizadordirecciones.Vista;

/**
 *
 * @author Pavilion
 */
public class JInternalFrameEstadoVisita extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameEstadoVisita
     */
    public JInternalFrameEstadoVisita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroRutero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAforador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLocalidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFrecuencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCtaContrato = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAviso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroAforo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtVna = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPd = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPqr = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado visita", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 2, 12))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(480, 270));
        jPanel1.setMinimumSize(new java.awt.Dimension(480, 270));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setText("Rutero N°:");

        txtNumeroRutero.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtNumeroRutero.setAutoscrolls(false);
        txtNumeroRutero.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtNumeroRutero.setMaximumSize(new java.awt.Dimension(145, 25));
        txtNumeroRutero.setMinimumSize(new java.awt.Dimension(145, 25));
        txtNumeroRutero.setPreferredSize(new java.awt.Dimension(145, 25));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("Aforador:");

        txtAforador.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtAforador.setAutoscrolls(false);
        txtAforador.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtAforador.setMaximumSize(new java.awt.Dimension(145, 25));
        txtAforador.setMinimumSize(new java.awt.Dimension(145, 25));
        txtAforador.setPreferredSize(new java.awt.Dimension(145, 25));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setText("Localidad:");

        txtLocalidad.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtLocalidad.setAutoscrolls(false);
        txtLocalidad.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtLocalidad.setMaximumSize(new java.awt.Dimension(145, 25));
        txtLocalidad.setMinimumSize(new java.awt.Dimension(145, 25));
        txtLocalidad.setPreferredSize(new java.awt.Dimension(145, 25));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setText("Frecuencia:");

        txtFrecuencia.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtFrecuencia.setAutoscrolls(false);
        txtFrecuencia.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtFrecuencia.setMaximumSize(new java.awt.Dimension(145, 25));
        txtFrecuencia.setMinimumSize(new java.awt.Dimension(145, 25));
        txtFrecuencia.setPreferredSize(new java.awt.Dimension(145, 25));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setText("Cta. Contrato");

        txtCtaContrato.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtCtaContrato.setAutoscrolls(false);
        txtCtaContrato.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtCtaContrato.setMaximumSize(new java.awt.Dimension(145, 25));
        txtCtaContrato.setMinimumSize(new java.awt.Dimension(145, 25));
        txtCtaContrato.setPreferredSize(new java.awt.Dimension(145, 25));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setText("Aviso");

        txtAviso.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtAviso.setAutoscrolls(false);
        txtAviso.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtAviso.setMaximumSize(new java.awt.Dimension(145, 25));
        txtAviso.setMinimumSize(new java.awt.Dimension(145, 25));
        txtAviso.setPreferredSize(new java.awt.Dimension(145, 25));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setText("Aforo N°");

        txtNumeroAforo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtNumeroAforo.setAutoscrolls(false);
        txtNumeroAforo.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtNumeroAforo.setMaximumSize(new java.awt.Dimension(145, 25));
        txtNumeroAforo.setMinimumSize(new java.awt.Dimension(145, 25));
        txtNumeroAforo.setPreferredSize(new java.awt.Dimension(145, 25));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setText("VNA");

        txtVna.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtVna.setAutoscrolls(false);
        txtVna.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtVna.setMaximumSize(new java.awt.Dimension(145, 25));
        txtVna.setMinimumSize(new java.awt.Dimension(145, 25));
        txtVna.setPreferredSize(new java.awt.Dimension(145, 25));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setText("PD");

        txtPd.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtPd.setAutoscrolls(false);
        txtPd.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtPd.setMaximumSize(new java.awt.Dimension(145, 25));
        txtPd.setMinimumSize(new java.awt.Dimension(145, 25));
        txtPd.setPreferredSize(new java.awt.Dimension(145, 25));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel10.setText("PO");

        txtPo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtPo.setAutoscrolls(false);
        txtPo.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtPo.setMaximumSize(new java.awt.Dimension(145, 25));
        txtPo.setMinimumSize(new java.awt.Dimension(145, 25));
        txtPo.setPreferredSize(new java.awt.Dimension(145, 25));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel11.setText("PQR");

        txtPqr.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtPqr.setAutoscrolls(false);
        txtPqr.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtPqr.setMaximumSize(new java.awt.Dimension(145, 25));
        txtPqr.setMinimumSize(new java.awt.Dimension(145, 25));
        txtPqr.setPreferredSize(new java.awt.Dimension(145, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroRutero, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtAforador, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(46, 46, 46)
                                    .addComponent(jLabel6)
                                    .addGap(79, 79, 79)
                                    .addComponent(jLabel7))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtCtaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(txtAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(txtNumeroAforo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(txtVna, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(txtPd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addGap(23, 23, 23)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(txtPqr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)
                        .addComponent(txtVna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNumeroRutero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtAforador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel11))))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCtaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroAforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPqr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(63, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 50, Short.MAX_VALUE)))
        );

        jPanel1.getAccessibleContext().setAccessibleName("EstadoVisita");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAforador;
    private javax.swing.JTextField txtAviso;
    private javax.swing.JTextField txtCtaContrato;
    private javax.swing.JTextField txtFrecuencia;
    private javax.swing.JTextField txtLocalidad;
    private javax.swing.JTextField txtNumeroAforo;
    private javax.swing.JTextField txtNumeroRutero;
    private javax.swing.JTextField txtPd;
    private javax.swing.JTextField txtPo;
    private javax.swing.JTextField txtPqr;
    private javax.swing.JTextField txtVna;
    // End of variables declaration//GEN-END:variables
}
